import {
  PawPrint,
  Dog,
  Cat,
  Bone,
  Heart,
  HeartPulse,
  Smile,
  Stethoscope,
  Shield,
  ShieldCheck,
  Activity,
  Pill,
  Syringe,
  Thermometer,
  Sparkles,
  VolumeX,
  Volume2,
  Moon,
  Feather,
  Wind,
  Bell,
  BellOff,
  Timer,
  Clock,
  Hourglass,
  CalendarCheck,
  Repeat,
  Zap,
  Gauge,
  DollarSign,
  Tag,
  Percent,
  PiggyBank,
  Wallet,
  TrendingDown,
  Award,
  BadgeCheck,
  Star,
  ThumbsUp,
  Check,
  CircleCheck,
  Lock,
  Truck,
  Package,
  PackageCheck,
  Box,
  Gift,
  ShoppingBag,
  RefreshCcw,
  RefreshCw,
  Home,
  Sofa,
  Sun,
  Leaf,
  Sprout,
  Droplet,
  Info,
  CircleHelp,
  TriangleAlert,
  Eye,
  Search,
  BatteryCharging,
  Plug,
  Settings,
  Wrench,
  Hand,
  Users,
  MessageCircle,
  Quote,
  Camera,
  type LucideIcon,
} from "lucide-react";

// The content-icon vocabulary, mirroring CONTENT_ICONS in the admin's
// lib/icons.ts (same lucide version, so the editor preview matches exactly).
//
// ONE map for every content field — FAQ items, hero bullets, comparison
// columns. Each used to keep its own hand-written map, and they drifted: the
// vet FAQ authored "Stethoscope" while the FAQ map knew only five names, so it
// silently rendered as a shield. Imports are explicit (not `import *`) so the
// bundle only carries icons that are actually selectable.
export const CONTENT_ICON_MAP: Record<string, LucideIcon> = {
  PawPrint, Dog, Cat, Bone, Heart, HeartPulse,
  Smile, Stethoscope, Shield, ShieldCheck, Activity, Pill,
  Syringe, Thermometer, Sparkles, VolumeX, Volume2, Moon,
  Feather, Wind, Bell, BellOff, Timer, Clock,
  Hourglass, CalendarCheck, Repeat, Zap, Gauge, DollarSign,
  Tag, Percent, PiggyBank, Wallet, TrendingDown, Award,
  BadgeCheck, Star, ThumbsUp, Check, CircleCheck, Lock,
  Truck, Package, PackageCheck, Box, Gift, ShoppingBag,
  RefreshCcw, RefreshCw, Home, Sofa, Sun, Leaf,
  Sprout, Droplet, Info, CircleHelp, TriangleAlert, Eye,
  Search, BatteryCharging, Plug, Settings, Wrench, Hand,
  Users, MessageCircle, Quote, Camera,
};

/** Resolve an authored icon name, falling back when it is unknown or absent. */
export function contentIcon(name: string | undefined, fallback: LucideIcon): LucideIcon {
  return (name && CONTENT_ICON_MAP[name]) || fallback;
}
